version: "3.9"

services:
  mongo:
    image: mongo
    container_name: ghibli-50-api-db
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  app:
    build: .
    container_name: ghibli-50-api
    environment:
      - MONGODB_URL=${DATABASE_URL}
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - mongo

volumes:
  mongo-data:
