version: "3.9"

services:
  postgres:
    image: postgres
    container_name: database_ghibli_50_api
    hostname: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=50api
      - POSTGRES_DB=ghibli-50-api
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: ghibli-50-api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
