version: "3.9"

services:
  postgres:
    image: postgres
    container_name: database_ghibli_50_api
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: ghibli-50-api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
